export const hauntedTruth = [
    "Has there been anything supernatural that you have actually experienced?",
    "What is the darkest secret you have kept from your friends?",
    "When was the last time you cheated on someone and why?",
    "If you had to sell your soul, what would you do it for?",
    "Who in this room are you most afraid of?",
    "Have you ever hurt someone intentionally?",
    "Do you have a cursed object or talisman?",
    "Have you ever believed that you were being haunted by a spirit?",
    "Tell me about the scariest dream that has haunted you for a long time.",
    "What secret do you not want to come out right now?",
    "Have you ever dabbled in the occult, conjured spirits, or played Ouija?",
    "Was there a time when you truly thought you were going to die?",
    "Tell me about a time when you felt like someone was watching you.",
    "If you were a ghost, who would you haunt?",
    "Is there anything in your house that scares you?",
    "What is your worst childhood trauma?",
    "When was the last time you lied to everyone here?",
    "What would you do if you found yourself in a haunted house?",
    "Have you ever thought that you could be reincarnated?",
    "Who do you think has the darkest soul?",
    "What are you hiding right now?",
    "Have you ever sensed the presence of a dead person?",
    "Have you ever believed in curses?",
    "Who is the least likely to survive a horror movie and why?",
    "If you were to disappear tonight, who would be to blame?",
    "What is your biggest taboo or fear?",
    "Has there ever been a time when your mind told you something was “wrong”… but you didn’t listen?",
    "Have you ever told someone about your nightmares? Which one was the scariest?",
    "Do you have a bad feeling right now?",
    "What secret will you take to the grave with you?"
];

export const hauntedDare = [
  "Walk through a room in the dark, reciting the passage of the spell in a whisper.",
  "Look someone in the eye for 30 seconds without blinking - silently.",
  "Say out loud: \"I call you who are hidden in the darkness\" - three times.",
  "Sit in the center of the room, close your eyes and do not move for 1 minute while others watch you.",
  "Tell a terrible secret that you have never told anyone - or visualize it.",
  "Take someone's hand and whisper a curse that you have just made up.",
  "Pretend that you have just been possessed by a spirit - 30 seconds.",
  "Write a short, creepy letter... to yourself.",
  "Hold a mirror in front of you and say: \"I see you\" - 5 times.",
  "Visualize how you would act if you were being chased by a ghost.",
  "Go out the door and knock three times, then slowly enter with the phrase \"He's already here...\"",
  "Choose another player and tell how he will die in a fictional story.",
  "Walk slowly around the room as if you are a ghost.",
  "Make a prediction: \"What will happen to you tonight?\"",
  "Write a scary phrase on a piece of paper and hide it in the pocket of another player.",
  "Try changing your voice as if you have just become someone else.",
  "Take the phone, record a message on the recorder as if from the other world.",
  "Ask the \"spirit\" for forgiveness for something you did not do.",
  "Act out a scene from your own nightmare.",
  "Let someone play your \"dark alter ego\" for one minute.",
  "Turn off the lights and say the phrase: \"Now I see something you can't see...\"",
  "Tell a scary story about this room as if it were real.",
  "Choose someone who must \"exorcise\" you because you are possessed.",
  "Write a short obituary about yourself and read it.",
  "Perform a creepy ghost dance from the past.",
  "Sitting with your back to everyone, say: \"Someone among you is not who you seem.\"",
  "Deliver a fictional message \"from the other world.\"",
  "Look out the window and describe what you see... as if it were a ghost.",
  "Ask yourself a question out loud as if the ghost is asking you.",
  "Whisper the phrase \"I am here, can you hear me?\" quietly and wait for a response."
];