const hauntedSpy = [
    "Abandoned library",
    "Corridor with mirrors",
    "Old photo lab",
    "Forgotten kindergarten",
    "Church dungeon",
    "Theatre basement",
    "Empty hospital ward #13",
    "Attic of an old house",
    "Ghost tram",
    "Abandoned living room",
    "Crypt with a closed name",
    "Lobby of the Meridian hotel",
    "Bridge through the fog",
    "Orangery without sun",
    "Wax museum",
    "Burnt house with windows without glass",
    "Grave without a name",
    "Forgotten room in school",
    "Ghost metro station",
    "Room with clocks",
    "Old psychiatrist's office",
    "Cemetery of names that do not exist",
    "One-session cinema",
    "Fireplace hall without fire",
    "Room with a music box",
    "Stairs leading to nowhere",
    "Elevator that going to the wrong floors",
    "Shadow Office",
    "Secret Tunnel Under the Monastery",
    "Bed in a Room Without a Door"
];

export default hauntedSpy;